Details page
lotus-1/Buddha pull request #31
Opened 2019-07-27 07:03 UTC by maha276

I created the form component and styled it.

2019-07-27 12:33 UTC, litalshl requested changes
Good job with the BuddhaInput!
Please pay attention to naming conventions, and no shortcuts for the names like CpDetails. It’s ok if the name is long. For example, CpDetails should be ContentPackageDetails.

2019-07-27 12:33 UTC, litalshl commented on src/front-end/CpDetailsPage.js
> +export default CpDetails;
Good work!
Please add a component BuddhaButtonWithLink that already has the Link as a parameter to make your code and others cleaner. Please collaborate with Sahar since she needs to use the same component.

2019-07-27 12:33 UTC, litalshl commented on src/front-end/CpSummary.js
> +          <CpSummaryButton
Why use CPSummaryButton and not BuddhaButton? CPSummaryButton should be deleted from the project.

2019-07-27 12:33 UTC, litalshl commented on src/front-end/CpSummary.js
> +class CpSummary extends React.Component {
Please change the class and file name to ContentPackageSummaryPage

2019-07-27 12:33 UTC, litalshl commented on src/front-end/buttons/allContentButtons.js
> +        </button>
Why do you need this component? 
If you need it, please make it more general so others can use it as well. Something like BuddhaButtonsPanel that will get any number of BuddhaButtons. Please look at the example in Slack for the table that gets the rows as parameter.

2019-07-27 12:33 UTC, litalshl commented on src/front-end/buttons/cpDetailsButtons.js
> +class CpDetailsButton extends React.Component {
Please remove this component or make it also general if it has any new details that BuddhaButton doesn’t have.

2019-07-27 12:33 UTC, litalshl commented on src/front-end/buttons/cpSummaryButtons.js
> +class CpSummaryButton extends React.Component {
Please delete this component, again it’s the same as BuddhaButton.

2019-07-27 12:33 UTC, litalshl commented on src/front-end/components/BuddhaInput.js
> +export default BuddhaInput;
Great job!

2019-07-27 12:33 UTC, litalshl commented on src/front-end/header/cpSummaryHeader.js
> +const myHeader = props => {
Please change it to a general component like BuddhaHeader and use it where appropriate with the specific properties.

2019-07-27 12:33 UTC, litalshl commented on src/front-end/input/cpDetailsInput.js
> +        <div className="detailsid">
Why aren’t you using the BuddhaInput you’ve created??

2019-07-27 12:33 UTC, litalshl commented on src/front-end/switch/switch.js
> +// // import React from "react";
Please delete the file if it’s not needed. Don’t comment out like this.

2019-07-27 12:33 UTC, litalshl commented on src/front-end/table/myContentTable.js
> -// export default myTable;
Again, delete the file.

2019-07-27 12:33 UTC, litalshl commented on src/front-end/table/cpSummaryTable.js
> +export default CpSummaryTable;
Please follow the example in Slack and collaborate with Sahar to create one BuddhaTable and use it everywhere.

2019-07-27 13:10 UTC, maha276 commented on src/front-end/CpDetailsPage.js
> +export default CpDetails;
Thank you for the review !
did you mean to add this lines in a new file with new component `BuddhaButtonWithLink` ?
`<Link to="/cpDetails">
          <BuddhaButton name="Details" variant="light" />
        </Link>
        <Link to="/cpAllocation">
          <BuddhaButton name="Allocation" variant="info" />
        </Link>
        <Link to="/cpSummary">
          <BuddhaButton name="Summary" variant="blue" />
        </Link>`

2019-07-27 13:47 UTC, maha276 commented on src/front-end/input/cpDetailsInput.js
> +        <div className="detailsid">
Yes I didn't need this file at all because I use this component in my `ContentPackageDetailsPage`

2019-07-27 13:48 UTC, maha276 commented on src/front-end/input/cpDetailsInput.js
> +        <div className="detailsid">
So I deleted this file.

2019-07-27 14:27 UTC, litalshl commented on src/front-end/CpDetailsPage.js
> +export default CpDetails;
I mean create a new button component called BuddhaButtonWithLink which will get the properties name, variant and link. It’s render will be:
<Link to={link}>
     <BuddhaButton name={name} variant={variant}>
.
.
.
And so on.

2019-07-27 16:07 UTC, litalshl approved these changes
Fix my last comment and then you can merge to sprint-2.
Good job!

2019-07-28 05:18 UTC, hanle11 commented on src/front-end/ContentPackageDetailsPage.js
> +    console.log(this.state);
Logging to console without clear explanation is creating messy console.
I recommend to either delete this log, or add more information to it

2019-07-28 05:24 UTC, hanle11 requested changes
This is a very big diff.
Many new classes, difficult to review.
This is causing also problems with the source control- this is the 3rd diff with the same code.
Please separate to smaller diffs: 
Refactoring of button should go to a separate diff.
Every new "class" should go to separate diff.
Abandon old diffs that you don't use anymore, because as a reviewer, I am not sure what is going on- which diff is up-to-date and which isn't.

2019-07-28 05:24 UTC, hanle11 commented on src/front-end/MyContentPackages.js
> +        <Link to="/cpSummary">
Use BuddhaButtonWithLink

2019-07-28 05:24 UTC, hanle11 commented on src/front-end/components/BuddhaButtonWithLink.js
> +      <div>
you can remove this div

2019-07-28 05:24 UTC, hanle11 commented on src/front-end/components/BuddhaButtonWithLink.js
> +class BuddhaButtonWithLink extends React.Component {
Instead of creating multiple files (BuddhaButton, BuddhaButtonWithLink), I recommend to have only 1 class- BuddhaButton.
Inside this class you can check if "link" was provided. If yes, wrap the button with link, if not, just return it without link.

2019-07-28 05:24 UTC, hanle11 commented on src/front-end/table/cpSummaryTable.js
> +class CpSummaryTable extends React.Component {
CpSummaryTable -> ContentPackageSummaryTable

2019-07-28 05:24 UTC, hanle11 commented on src/front-end/table/cpSummaryTable.css
> +/* .tableHeader {
delete.
Don't commit comments

2019-07-28 05:24 UTC, hanle11 commented on src/front-end/header/cpSummaryHeader.js
> +const myHeader = props => {
This is the 3rd diff that I see with same new code....
Is there a problem with the diffs?

2019-07-28 16:27 UTC, merged